### ISSUE TITLE
cannot find annotations noise

### ISSUE THREAD

**Issue by xenoterracide** [immutables/immutables#1509]
This... is... obnoxiousness

```
/home/xeno/.gradle/wrapper/dists/gradle-8.7-bin/bhs2wmbdwecv87pi65oeuq5iu/gradle-8.7/lib/guava-32.1.2-jre.jar(/com/google/common/base/Optional.class): warning: Cannot find annotation method 'value()' in type 'DoNotMock': class file for com.google.errorprone.annotations.DoNotMock not found
/home/xeno/.gradle/wrapper/dists/gradle-8.7-bin/bhs2wmbdwecv87pi65oeuq5iu/gradle-8.7/lib/guava-32.1.2-jre.jar(/com/google/common/base/Strings.class): warning: Cannot find annotation method 'replacement()' in type 'InlineMe': class file for com.google.errorprone.annotations.InlineMe not found
/home/xeno/.gradle/wrapper/dists/gradle-8.7-bin/bhs2wmbdwecv87pi65oeuq5iu/gradle-8.7/lib/guava-32.1.2-jre.jar(/com/google/common/base/Strings.class): warning: Cannot find annotation method 'value()' in type 'InlineMeValidationDisabled': class file for com.google.errorprone.annotations.InlineMeValidationDisabled not found
```

here's a snippet of my setup

```toml
immutables-bom = "org.immutables:bom:2+"
immutables-annotations = { module = "org.immutables:value-annotations" }
immutables-builder = { module = "org.immutables:builder" }
immutables-core = { module = "org.immutables:value" }
immutables = ["immutables-annotations", "immutables-builder"]
```

```kts
  annotationProcessor(platform(libs.spring.bom))
  annotationProcessor(platform(libs.immutables.bom))
  annotationProcessor(libs.immutables.core)
  annotationProcessor(libs.hibernate.jpa.modelgen)

  compileOnly(platform(libs.immutables.bom))
  compileOnly(libs.bundles.immutables)
  compileOnly(libs.jspecify)
  compileOnly(libs.java.tools)
  compileOnly(libs.jakarta.annotation)
```

can I get rid of these warnings? more importantly, is there a way to get it not to poke at gradle jars?
